### ISSUE TITLE
Logging in with Admin account doesn't seem to work

### ISSUE THREAD

**Issue by justinlevi** [auth0/auth0-drupal#90] opened 2018-03-23 18:47 UTC
Hey gang, I'm finding the readme.txt and any instructions very confusing.  Here's what we have in the technical notes:

> TECHNICAL NOTES
> ---------------
> 
> **IMPORTANT**: By using this plugin you are delegating the site authentication
> to Auth0. That means that you won't be using the drupal database to authenticate
> users anymore and the default login box won't show anymore. However, we can
> still associate your existing users by merging them by email. This section
> explains how.
> 
> When you install this plugin you have at least one existing user in the
> database (the admin user). If the site is already being used, you probably have
> more than just the admin. We want you to keep those users, of course.
> 
> Auth0 allows multiple authentication providers. You can have social providers
> like Facebook, Twitter, Google+, etc., you can have a database of
> users/passwords (just like drupal but hosted in Auth0) or you can use an
> Enterprise directory like Active Directory, LDAP, Office365, SAML and others.
> All those authentication providers might give you an email and a flag indicating
> whether the email was verified or not. We use that email (only if its verified)
> to associate a previous **existing** user with the one coming from Auth0.

The last line of the first paragraph states: "This section explains how". However, I don't actually see any information for how to get an existing drupal database users to be authenticated with Auth0. 

How would you setup Auth0 to work with your local database during development? I've tried to go through and add a database connection and use my own local database credentials but nothing seems to work.

**Comment by joshcanhelp** [comment] 2018-03-28 14:21
More or less a duplicate of #91. Will answer there.

**Closed by joshcanhelp** 2018-03-28 14:21 UTC
